# Generated by Django 5.2.13 on 2026-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDContract', models.CharField(max_length=7)),
                ('Name', models.CharField(max_length=100)),
                ('IDCustomer', models.CharField(max_length=6)),
                ('Type', models.CharField(max_length=1)),
                ('Address', models.CharField(max_length=200)),
                ('DateCreated', models.DateField(blank=True, null=True)),
                ('DateRun', models.DateField(blank=True, null=True)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(blank=True)),
            ],
        ),
    ]
