# Generated by Django 5.2.13 on 2026-05-23 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0001_initial'),
        ('Customer', '0002_alter_customer_options_alter_customer_idkredit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['IDContract']},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='IDCustomer',
        ),
        migrations.AddField(
            model_name='contract',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contract',
            name='Type',
            field=models.CharField(choices=[('A', 'Autobahn'), ('F', 'Flughafen'), ('S', 'Stadt')], max_length=1),
        ),
    ]
