# Generated by Django 5.2.13 on 2026-05-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0002_alter_contract_options_remove_contract_idcustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='City',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
