# Generated by Django 5.2.13 on 2026-06-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contract', '0003_contract_city'),
        ('Warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stencil', models.CharField(choices=[('not_needed', '❌ Not Needed'), ('available', '✅ Available'), ('ordered', '📦 Ordered')], default='not_needed', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Contract.contract')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_materials', to='Warehouse.material')),
            ],
            options={
                'unique_together': {('contract', 'material')},
            },
        ),
    ]
