# Generated by Django 5.2.13 on 2026-05-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCustomer', models.CharField(max_length=6)),
                ('IDKredit', models.CharField(max_length=10)),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('PostCode', models.CharField(blank=True, max_length=20)),
                ('MobileNumber1', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
