# Generated by Django 5.2.13 on 2026-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['IDCustomer']},
        ),
        migrations.AlterField(
            model_name='customer',
            name='IDKredit',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
