# Generated by Django 5.2.13 on 2026-06-08 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contract', '0003_contract_city'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cold_plastic', 'Kaltplastik'), ('hot_plastic', 'Heißplastik'), ('roll_plastic', 'Rollplastik'), ('paint', 'Farbe'), ('hardener', 'Härter'), ('pearl', 'Perlen')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', '📥 Eingang'), ('out', '📤 Ausgabe'), ('return', '↩️ Rückgabe'), ('used', '✅ Verbrauch')], max_length=10)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='Contract.contract')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Warehouse.material')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
