# Generated by Django 5.2.15 on 2026-07-05 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='photo',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_employment', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '✅ Active'), ('vacation', '🏖️ Vacation'), ('sick', '🤒 Sick'), ('terminated', '❌ Terminated')], default='active', max_length=20)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('license_B', models.BooleanField(default=False)),
                ('license_BE', models.BooleanField(default=False)),
                ('license_C', models.BooleanField(default=False)),
                ('license_C1', models.BooleanField(default=False)),
                ('license_CE', models.BooleanField(default=False)),
                ('license_liftruck', models.BooleanField(default=False)),
                ('exp_autobahn', models.BooleanField(default=False)),
                ('exp_airport', models.BooleanField(default=False)),
                ('exp_city', models.BooleanField(default=False)),
                ('shoe_size', models.IntegerField(blank=True, null=True)),
                ('tshirt_size', models.CharField(blank=True, max_length=5, null=True)),
                ('pants_size', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clothing_type', models.CharField(choices=[('jacket', '🧥 Jacket'), ('pants', '👖 Pants'), ('shirt', '👕 T-Shirt'), ('vest_hi', '🦺 Hi-Vis Vest'), ('vest_safety', '🦺 Safety Vest'), ('shoes', '👟 Shoes'), ('helmet', '⛑️ Helmet')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_issues', to='Accounts.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
