# Generated by Django 5.2.13 on 2026-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('RegisterNumber', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Kennzeichen')),
                ('Model', models.IntegerField(choices=[(1, 'Ford'), (2, 'Skoda'), (3, 'Volkswagen'), (4, 'Man'), (5, 'Iveco'), (6, 'Mercedes Benz'), (7, 'Henne Richard'), (8, 'Winter'), (9, 'Partenheimer'), (10, 'Obermaier'), (11, 'Trebbiner'), (12, 'T-AX-O Trailer'), (13, 'Humbaur'), (14, 'Zeppelin'), (15, 'WM Meyer'), (18, 'Hyundai')], default=1)),
                ('Kind', models.IntegerField(blank=True, choices=[(1, 'Kehrmaschine'), (2, 'LKW Offener Kasten'), (3, 'Sprinter'), (4, 'LKW Thermo Kocher'), (9, 'Markierungsmaschine'), (15, 'Transit'), (16, 'Crafter'), (17, 'Vito')], null=True)),
                ('Fuel', models.IntegerField(blank=True, choices=[(1, 'Benzin'), (2, 'Dieselöl'), (3, 'E-Auto'), (4, 'Hybrid')], null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='vehicles/')),
                ('Description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['RegisterNumber'],
            },
        ),
    ]
