# Generated by Django 5.2.13 on 2026-05-27 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Versicherung läuft ab'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometerstand'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kaufdatum'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Verantwortlicher'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='technical_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='HU/TÜV läuft ab'),
        ),
    ]
