# Generated by Django 5.2.13 on 2026-05-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='type',
            new_name='leave_type',
        ),
    ]
