# Generated by Django 5.2.13 on 2026-05-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0003_leaverequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ill', 'Krank'), ('holiday', 'Urlaub')], default='holiday', max_length=20),
        ),
    ]
