# Generated by Django 5.2.15 on 2026-07-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='max_holiday_days',
            field=models.IntegerField(default=30),
        ),
    ]
