# Generated by Django 5.2.13 on 2026-05-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0001_initial'),
        ('Vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='workdays', to='Vehicle.vehicle'),
        ),
    ]
