# Generated by Django 5.2.13 on 2026-05-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0002_workday_vehicles'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='shift',
            field=models.CharField(choices=[('day', '🌞 Day (06:00 - 18:00)'), ('night', '🌙 Night (18:00 - 06:00)')], default='day', max_length=10),
        ),
    ]
