# Generated by Django 5.2.13 on 2026-05-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0003_workday_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='status',
            field=models.CharField(choices=[('planned', '📅 Planned'), ('done', '✅ Done'), ('cancelled_client', '❌ Cancelled by Client'), ('cancelled_contractor', '❌ Cancelled by Contractor'), ('cancelled_weather', '🌧️ Cancelled by Weather')], default='planned', max_length=30),
        ),
    ]
