# Generated by Django 5.2.13 on 2026-05-28 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0004_workday_cancel_reason_workday_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDayWorkerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('workday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_notes', to='Schedule.workday')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workday_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('workday', 'worker')},
            },
        ),
    ]
