# Generated by Django 5.2.15 on 2026-07-06 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schedule', '0006_workreport_workreportimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReportAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='reports/audio/')),
                ('duration', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='Schedule.workreport')),
            ],
        ),
    ]
